# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\Dell Latitude 5420\OneDrive\Bureau\phase_3\login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(480, 620)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(210, 140, 151, 61))
        self.label.setStyleSheet(" font-size:24pt;\n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 250, 131, 31))
        self.label_2.setStyleSheet("font-size:15pt; \n"
"background-color: rgb(255, 170, 0);\n"
"color: rgb(0, 0, 0);")
        self.label_2.setObjectName("label_2")
        self.email = QtWidgets.QLineEdit(Dialog)
        self.email.setGeometry(QtCore.QRect(180, 240, 241, 51))
        self.email.setStyleSheet("font-size:14pt; \n"
"color: rgb(0, 0, 0);")
        self.email.setObjectName("email")
        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(170, 340, 241, 51))
        self.password.setStyleSheet("font-size:14pt; color:rgb(0,0,0)")
        self.password.setText("")
        self.password.setObjectName("password")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 350, 131, 31))
        self.label_3.setStyleSheet("font-size:15pt; \n"
"color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 170, 0);")
        self.label_3.setObjectName("label_3")
        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(250, 430, 141, 41))
        self.loginbutton.setStyleSheet(" font-size:14pt; color:rgb(255, 255, 255);\n"
"background-color: rgb(85, 170, 255);")
        self.loginbutton.setObjectName("loginbutton")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 70, 191, 41))
        self.label_4.setStyleSheet("image: url(:/img/Logo_-_Maghreb_Steel_(1).jpg);")
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Login"))
        self.label_2.setText(_translate("Dialog", "User"))
        self.label_3.setText(_translate("Dialog", "Password"))
        self.loginbutton.setText(_translate("Dialog", "Login"))
import res_rc
